kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-1-replica
annotations:
  storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "xfs"
