apiVersion: apps/v1
kind: Deployment
metadata:
  name: longhorn-ui
spec:
  template:
    spec:
      containers:
        - name: longhorn-ui
          env:
            - name: DEFAULT_SETTING_DEFAULT_REPLICA_COUNT
              value: "1"
