apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ozeliurs/dunite-kub.git
    targetRevision: HEAD
    path: workloads/apps/cf
  destination:
    server: https://kubernetes.default.svc
    namespace: cf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
