apiVersion: apps/v1
kind: Deployment
metadata:
  name: hedgedoc-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hedgedoc-db
  template:
    metadata:
      labels:
        app: hedgedoc-db
    spec:
      containers:
        - name: postgres
          image: postgres:13-alpine
          env:
            - name: POSTGRES_USER
              value: "hedgedoc"
            - name: POSTGRES_DB
              value: "hedgedoc"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hedgedoc-secrets
                  key: postgres-password
          volumeMounts:
            - name: hedgedoc-db-data
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - hedgedoc
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: hedgedoc-db-data
          persistentVolumeClaim:
            claimName: hedgedoc-db-pvc
